export interface Metier {
  code: string;
  nom: string;
}

export interface Secteur {
  code: string;
  nom: string;
  metiers: Metier[];
}

export const SECTEURS: Secteur[] = [
  {
    code: "BTP",
    nom: "BTP - Génie civil - Travaux publics",
    metiers: [
      { code: "BTP001", nom: "Manœuvre BTP" },
      { code: "BTP002", nom: "Maçon" },
      { code: "BTP003", nom: "Coffreur" },
      { code: "BTP004", nom: "Ferrailleur" },
      { code: "BTP005", nom: "Carreleur" },
      { code: "BTP006", nom: "Staffeur" },
      { code: "BTP007", nom: "Peintre Bâtiment" },
      { code: "BTP008", nom: "Chef d'équipe BTP" },
      { code: "BTP009", nom: "Chef de chantier" },
      { code: "BTP010", nom: "Conducteur d'engins lourds" },
      { code: "BTP011", nom: "Topographe" },
      { code: "BTP012", nom: "Géomètre" },
      { code: "BTP013", nom: "Technicien Laboratoire BTP" },
      { code: "BTP014", nom: "Ingénieur Génie Civil" },
      { code: "BTP015", nom: "Ingénieur Travaux Publics" },
      { code: "BTP016", nom: "Architecte" },
      { code: "BTP017", nom: "Dessinateur Bâtiment" },
    ],
  },
  {
    code: "ELE",
    nom: "Électricité - Énergie - Froid - Clim",
    metiers: [
      { code: "ELE001", nom: "Électricien Bâtiment" },
      { code: "ELE002", nom: "Électricien Industriel" },
      { code: "ELE003", nom: "Électromécanicien" },
      { code: "ELE004", nom: "Bobineur" },
      { code: "ELE005", nom: "Installateur Solaire" },
      { code: "ELE006", nom: "Technicien Énergie Renouvelable" },
      { code: "ELE007", nom: "Frigoriste" },
      { code: "ELE008", nom: "Technicien Froid et Climatisation" },
      { code: "ELE009", nom: "Technicien Groupe Électrogène" },
      { code: "ELE010", nom: "Ingénieur Électricité" },
      { code: "ELE011", nom: "Ingénieur Électrotechnique" },
      { code: "ELE012", nom: "Ingénieur Énergies" },
    ],
  },
  {
    code: "PLB",
    nom: "Plomberie - Menuiserie - Soudure - Mécanique",
    metiers: [
      { code: "PLB001", nom: "Plombier" },
      { code: "PLB002", nom: "Plombier Sanitaire" },
      { code: "PLB003", nom: "Menuisier Bois" },
      { code: "PLB004", nom: "Menuisier Alu" },
      { code: "PLB005", nom: "Menuisier Métallique" },
      { code: "PLB006", nom: "Soudeur" },
      { code: "PLB007", nom: "Chaudronnier" },
      { code: "PLB008", nom: "Tuyauteur" },
      { code: "PLB009", nom: "Mécanicien Auto" },
      { code: "PLB010", nom: "Mécanicien Poids Lourds" },
      { code: "PLB011", nom: "Mécanicien Engins" },
      { code: "PLB012", nom: "Tôlier" },
      { code: "PLB013", nom: "Peintre Auto" },
      { code: "PLB014", nom: "Vulcanisateur" },
      { code: "PLB015", nom: "Électricien Auto" },
    ],
  },
  {
    code: "TRA",
    nom: "Transport - Logistique - Transit - Stock",
    metiers: [
      { code: "TRA001", nom: "Chauffeur (Permis B)" },
      { code: "TRA002", nom: "Chauffeur (Permis C)" },
      { code: "TRA003", nom: "Chauffeur (Permis D)" },
      { code: "TRA004", nom: "Chauffeur (Permis E)" },
      { code: "TRA005", nom: "Chauffeur Personnel" },
      { code: "TRA006", nom: "Moto-taximan" },
      { code: "TRA007", nom: "Conducteur Tricycle" },
      { code: "TRA008", nom: "Magasinier" },
      { code: "TRA009", nom: "Gestionnaire de Stock" },
      { code: "TRA010", nom: "Cariste" },
      { code: "TRA011", nom: "Manutentionnaire" },
      { code: "TRA012", nom: "Logisticien" },
      { code: "TRA013", nom: "Approvisionneur" },
      { code: "TRA014", nom: "Transitaire" },
      { code: "TRA015", nom: "Déclarant en Douane" },
      { code: "TRA016", nom: "Responsable Parc Auto" },
    ],
  },
  {
    code: "AGR",
    nom: "Agriculture - Élevage - Agroalimentaire - Environnement",
    metiers: [
      { code: "AGR001", nom: "Ouvrier Agricole" },
      { code: "AGR002", nom: "Planteur" },
      { code: "AGR003", nom: "Technicien Agricole" },
      { code: "AGR004", nom: "Conseiller Agricole" },
      { code: "AGR005", nom: "Éleveur" },
      { code: "AGR006", nom: "Vétérinaire" },
      { code: "AGR007", nom: "Zootechnicien" },
      { code: "AGR008", nom: "Agronome" },
      { code: "AGR009", nom: "Ingénieur Agronome" },
      { code: "AGR010", nom: "Transformateur Agroalimentaire" },
      { code: "AGR011", nom: "Meunier" },
      { code: "AGR012", nom: "Boulanger" },
      { code: "AGR013", nom: "Pâtissier" },
      { code: "AGR014", nom: "Environnementaliste" },
      { code: "AGR015", nom: "Agent HSE / QHSE" },
    ],
  },
  {
    code: "HOT",
    nom: "Hôtellerie - Restauration - Tourisme",
    metiers: [
      { code: "HOT001", nom: "Serveur" },
      { code: "HOT002", nom: "Barman" },
      { code: "HOT003", nom: "Barmaid" },
      { code: "HOT004", nom: "Cuisinier" },
      { code: "HOT005", nom: "Commis de Cuisine" },
      { code: "HOT006", nom: "Grillardin" },
      { code: "HOT007", nom: "Réceptionniste" },
      { code: "HOT008", nom: "Gouvernante" },
      { code: "HOT009", nom: "Femme de Chambre" },
      { code: "HOT010", nom: "Agent d'Entretien" },
      { code: "HOT011", nom: "Nettoyage Industriel" },
      { code: "HOT012", nom: "Guide Touristique" },
      { code: "HOT013", nom: "Agent de Tourisme" },
    ],
  },
  {
    code: "COM",
    nom: "Commerce - Vente - Marketing - Communication",
    metiers: [
      { code: "COM001", nom: "Vendeur / Vendeuse en Boutique" },
      { code: "COM002", nom: "Commercial Terrain" },
      { code: "COM003", nom: "Téléconseiller" },
      { code: "COM004", nom: "Délégué Médical" },
      { code: "COM005", nom: "Commercial Pharmacie" },
      { code: "COM006", nom: "Caissier" },
      { code: "COM007", nom: "Rayonniste" },
      { code: "COM008", nom: "Merchandiser" },
      { code: "COM009", nom: "Animateur Commercial" },
      { code: "COM010", nom: "Marketeur" },
      { code: "COM011", nom: "Community Manager" },
      { code: "COM012", nom: "Infographiste" },
      { code: "COM013", nom: "Secrétaire Commerciale" },
      { code: "COM014", nom: "Assistante de Direction" },
    ],
  },
  {
    code: "ADM",
    nom: "Administration - Gestion - Finance - RH - Droit",
    metiers: [
      { code: "ADM001", nom: "Secrétaire" },
      { code: "ADM002", nom: "Secrétaire Comptable" },
      { code: "ADM003", nom: "Standardiste" },
      { code: "ADM004", nom: "Assistant Administratif" },
      { code: "ADM005", nom: "Agent Administratif" },
      { code: "ADM006", nom: "Comptable" },
      { code: "ADM007", nom: "Aide-Comptable" },
      { code: "ADM008", nom: "Caissier Comptable" },
      { code: "ADM009", nom: "Contrôleur de Gestion" },
      { code: "ADM010", nom: "Auditeur" },
      { code: "ADM011", nom: "Fiscaliste" },
      { code: "ADM012", nom: "Gestionnaire RH" },
      { code: "ADM013", nom: "Gestionnaire Paie" },
      { code: "ADM014", nom: "Chargé de Recrutement" },
      { code: "ADM015", nom: "Juriste" },
      { code: "ADM016", nom: "Assistant Juridique" },
      { code: "ADM017", nom: "Huissier" },
      { code: "ADM018", nom: "Directeur" },
      { code: "ADM019", nom: "Chef de Service" },
      { code: "ADM020", nom: "Superviseur" },
    ],
  },
  {
    code: "SAN",
    nom: "Santé - Pharmacie - Social",
    metiers: [
      { code: "SAN001", nom: "Aide-Soignant" },
      { code: "SAN002", nom: "Infirmier" },
      { code: "SAN003", nom: "Sage-Femme" },
      { code: "SAN004", nom: "Médecin" },
      { code: "SAN005", nom: "Pharmacien" },
      { code: "SAN006", nom: "Laborantin" },
      { code: "SAN007", nom: "Délégué Médical" },
      { code: "SAN008", nom: "Agent de Santé Communautaire" },
      { code: "SAN009", nom: "Assistant Social" },
    ],
  },
  {
    code: "EDU",
    nom: "Éducation - Formation",
    metiers: [
      { code: "EDU001", nom: "Enseignant Maternelle" },
      { code: "EDU002", nom: "Enseignant Primaire" },
      { code: "EDU003", nom: "Enseignant Secondaire" },
      { code: "EDU004", nom: "Professeur Université" },
      { code: "EDU005", nom: "Formateur Professionnel" },
      { code: "EDU006", nom: "Surveillant" },
      { code: "EDU007", nom: "Moniteur" },
    ],
  },
  {
    code: "INF",
    nom: "Informatique - Télécom - Digital",
    metiers: [
      { code: "INF001", nom: "Secrétaire Bureautique" },
      { code: "INF002", nom: "Opérateur de Saisie" },
      { code: "INF003", nom: "Technicien Maintenance Informatique" },
      { code: "INF004", nom: "Technicien Réseau" },
      { code: "INF005", nom: "Développeur Web" },
      { code: "INF006", nom: "Développeur Mobile" },
      { code: "INF007", nom: "Développeur Logiciel" },
      { code: "INF008", nom: "Administrateur Réseau" },
      { code: "INF009", nom: "Administrateur Système" },
      { code: "INF010", nom: "Administrateur Base de Données" },
      { code: "INF011", nom: "Technicien Télécom" },
      { code: "INF012", nom: "Technicien Fibre Optique" },
      { code: "INF013", nom: "Designer" },
      { code: "INF014", nom: "Monteur Vidéo" },
      { code: "INF015", nom: "Photographe" },
    ],
  },
  {
    code: "SEC",
    nom: "Sécurité - Artisanat - Services divers",
    metiers: [
      { code: "SEC001", nom: "Agent de Sécurité" },
      { code: "SEC002", nom: "Vigile" },
      { code: "SEC003", nom: "Garde du Corps" },
      { code: "SEC004", nom: "Coiffeur / Coiffeuse" },
      { code: "SEC005", nom: "Esthéticienne" },
      { code: "SEC006", nom: "Couturier" },
      { code: "SEC007", nom: "Cireur" },
      { code: "SEC008", nom: "Blanchisseur" },
      { code: "SEC009", nom: "Call Boxeur" },
      { code: "SEC010", nom: "Agent Mobile Money (MTN/Orange)" },
    ],
  },
  {
    code: "MIN",
    nom: "Mines - Pétrole - Industrie",
    metiers: [
      { code: "MIN001", nom: "Foreur" },
      { code: "MIN002", nom: "Technicien Pétrolier" },
      { code: "MIN003", nom: "Géologue" },
      { code: "MIN004", nom: "Ingénieur Mines" },
      { code: "MIN005", nom: "Opérateur Usine" },
      { code: "MIN006", nom: "Technicien de Production" },
    ],
  },
];

export const NIVEAUX_QUALIFICATION = [
  "Informel / Ouvrier",
  "Technique / Agent de maîtrise",
  "Supérieur / Cadre",
];

export function getMetiersDuSecteur(secteurNom: string): Metier[] {
  return SECTEURS.find((s) => s.nom === secteurNom)?.metiers ?? [];
}

export function getMetierCode(secteurNom: string, metierNom: string): string {
  return (
    getMetiersDuSecteur(secteurNom).find((m) => m.nom === metierNom)?.code ?? ""
  );
}